"""
Market Regime Detector — Bull/Bear/Crisis Identification
==========================================================
Citibank Oil Price Risk Factor Challenge

Identifies which "state" the oil market is in and shows how
the key risk factors CHANGE depending on the regime.

This is the competition differentiator: most teams say "USD and VIX
drive oil prices." This module shows that the TOP factors are DIFFERENT
in bull markets vs bear markets vs crises.

THREE DETECTION METHODS:
  1. Hidden Markov Model (HMM) — learns hidden states from returns + volatility
  2. K-Means Clustering — groups similar trading days together
  3. Rule-Based — explicit thresholds (drawdown > 20% = crisis)

OUTPUTS (in data/regime/):
  regime_labels.csv              ← every trading day labeled with its regime
  regime_factor_importance.csv   ← XGBoost feature importance PER regime
  regime_report.txt              ← stats, transitions, crisis periods
  regime_summary.json            ← for the API/frontend
  plots/                         ← 6 visualization charts

HOW TO RUN:
  pip install hmmlearn xgboost
  python regime_detector.py
"""

import json, warnings
from datetime import datetime
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

warnings.filterwarnings('ignore')

from config import PATHS

REGIME_DIR = PATHS.data_root / "regime"
PLOT_DIR = REGIME_DIR / "plots"
REGIME_DIR.mkdir(parents=True, exist_ok=True)
PLOT_DIR.mkdir(parents=True, exist_ok=True)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DATA LOADING
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def load_data():
    if not PATHS.price_featured.exists():
        print("  ✗ No price data found. Run oil_data_collector.py first.")
        return None
    df = pd.read_csv(str(PATHS.price_featured), index_col=0, parse_dates=True)
    print(f"  ✓ Loaded {len(df)} rows, {df.index.min().date()} → {df.index.max().date()}")
    return df


def prepare_regime_features(df):
    """Extract the features used for regime detection."""
    features = pd.DataFrame(index=df.index)

    if "WTI_Crude_Close" in df.columns:
        price = df["WTI_Crude_Close"]
        features["return_1d"] = price.pct_change()
        features["return_5d"] = price.pct_change(5)
        features["return_20d"] = price.pct_change(20)
        features["volatility_20d"] = features["return_1d"].rolling(20).std() * np.sqrt(252)

        # Drawdown from rolling max
        rolling_max = price.rolling(252, min_periods=20).max()
        features["drawdown"] = (price - rolling_max) / rolling_max

        # Price relative to 200-day MA
        ma200 = price.rolling(200, min_periods=50).mean()
        features["price_vs_ma200"] = (price - ma200) / ma200

    if "VIX_Close" in df.columns:
        features["vix"] = df["VIX_Close"]

    if "RSI_14" in df.columns:
        features["rsi"] = df["RSI_14"]

    features = features.dropna()
    print(f"  ✓ Regime features: {len(features)} rows, {features.shape[1]} columns")
    return features


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# METHOD 1: HIDDEN MARKOV MODEL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def detect_hmm(features, n_states=3):
    """
    Hidden Markov Model — the gold standard for regime detection.

    The idea: the market has hidden "states" (bull, bear, crisis) that
    we can't directly observe. But the returns and volatility we DO see
    are generated by whichever state is active. HMM figures out which
    state was most likely active on each day.
    """
    print("\n  [HMM] Training Hidden Markov Model...")
    try:
        from hmmlearn.hmm import GaussianHMM

        obs_cols = ["return_1d", "volatility_20d"]
        if "vix" in features.columns:
            obs_cols.append("vix")

        X = features[obs_cols].values

        model = GaussianHMM(
            n_components=n_states,
            covariance_type="full",
            n_iter=200,
            random_state=42
        )
        model.fit(X)
        states = model.predict(X)

        # Label states by average return (highest = bull)
        state_returns = {}
        for s in range(n_states):
            mask = states == s
            state_returns[s] = features["return_1d"].values[mask].mean()

        sorted_states = sorted(state_returns.keys(), key=lambda s: state_returns[s], reverse=True)
        names = ["bull", "bear", "crisis"]
        label_map = {sorted_states[i]: names[i] for i in range(n_states)}

        labels = pd.Series([label_map[s] for s in states], index=features.index, name="hmm_regime")
        print(f"  [HMM] ✓ States: {dict(labels.value_counts())}")
        return labels

    except ImportError:
        print("  [HMM] ✗ hmmlearn not installed. Run: pip install hmmlearn")
        return None
    except Exception as e:
        print(f"  [HMM] ✗ Error: {e}")
        return None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# METHOD 2: K-MEANS CLUSTERING
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def detect_kmeans(features, n_clusters=3):
    """
    K-Means — simpler alternative to HMM.
    Groups trading days into clusters based on similarity.
    """
    print("\n  [K-Means] Clustering...")
    try:
        from sklearn.cluster import KMeans
        from sklearn.preprocessing import StandardScaler

        cols = ["return_1d", "volatility_20d", "drawdown"]
        if "vix" in features.columns:
            cols.append("vix")

        X = features[cols].values
        X_scaled = StandardScaler().fit_transform(X)

        model = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        clusters = model.fit_predict(X_scaled)

        cluster_returns = {}
        for c in range(n_clusters):
            mask = clusters == c
            cluster_returns[c] = features["return_1d"].values[mask].mean()

        sorted_clusters = sorted(cluster_returns.keys(), key=lambda c: cluster_returns[c], reverse=True)
        names = ["bull", "bear", "crisis"]
        label_map = {sorted_clusters[i]: names[i] for i in range(n_clusters)}

        labels = pd.Series([label_map[c] for c in clusters], index=features.index, name="kmeans_regime")
        print(f"  [K-Means] ✓ Clusters: {dict(labels.value_counts())}")
        return labels

    except Exception as e:
        print(f"  [K-Means] ✗ Error: {e}")
        return None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# METHOD 3: RULE-BASED
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def detect_rulebased(features):
    """
    Explicit rules — the most transparent method.
    Easy to explain: "crisis = drawdown > 20% or volatility > 45%."
    """
    print("\n  [Rules] Applying rule-based detection...")

    labels = pd.Series("bear", index=features.index, name="rule_regime")

    crisis_mask = (features["drawdown"] < -0.20) | (features["volatility_20d"] > 0.45)
    labels[crisis_mask] = "crisis"

    if "price_vs_ma200" in features.columns:
        bull_mask = (
            (features["price_vs_ma200"] > 0) &
            (features["return_20d"] > 0) &
            (~crisis_mask)
        )
        labels[bull_mask] = "bull"

    print(f"  [Rules] ✓ Regimes: {dict(labels.value_counts())}")
    return labels


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FACTOR IMPORTANCE PER REGIME
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def compute_factor_importance(df, regime_labels):
    """
    Train a separate XGBoost for each regime and compare importance.
    THIS is the key competition insight.
    """
    print("\n  [Importance] Computing per-regime factor importance...")

    try:
        from xgboost import XGBRegressor
    except ImportError:
        print("  ✗ xgboost not installed. Run: pip install xgboost")
        return None

    common_idx = df.index.intersection(regime_labels.index)
    df_aligned = df.loc[common_idx].copy()
    df_aligned["regime"] = regime_labels.loc[common_idx].values

    feature_cols = [c for c in df_aligned.columns if c not in [
        'Target_Return_1d', 'regime', 'WTI_Crude_Open', 'WTI_Crude_High',
        'WTI_Crude_Low', 'WTI_Crude_Volume'
    ] and df_aligned[c].dtype in ['float64', 'int64', 'float32', 'int32']]

    if 'Target_Return_1d' not in df_aligned.columns:
        print("  ✗ No target column found")
        return None

    results = {}

    for regime in df_aligned["regime"].unique():
        subset = df_aligned[df_aligned["regime"] == regime]
        if len(subset) < 50:
            print(f"    {regime}: skipped ({len(subset)} rows, need 50+)")
            continue

        X = subset[feature_cols].dropna(axis=1, how='all')
        y = subset['Target_Return_1d']
        valid = X.index.intersection(y.dropna().index)
        X, y = X.loc[valid], y.loc[valid]

        if len(X) < 50:
            continue

        model = XGBRegressor(
            n_estimators=100, max_depth=4, learning_rate=0.05,
            random_state=42, verbosity=0
        )
        model.fit(X, y)

        importance = dict(zip(X.columns, model.feature_importances_.tolist()))
        top = sorted(importance.items(), key=lambda x: x[1], reverse=True)[:10]
        results[regime] = top

        print(f"    {regime} ({len(X)} days): top 3 = {', '.join([f[0] for f in top[:3]])}")

    return results


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# VISUALIZATIONS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COLORS = {"bull": "#27ae60", "bear": "#e67e22", "crisis": "#e74c3c"}

def _save(fig, name):
    fig.savefig(PLOT_DIR / name, dpi=170, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"    ✓ {name}")


def plot_price_with_regimes(df, labels):
    """01 — Price history colored by regime."""
    if "WTI_Crude_Close" not in df.columns:
        return
    common = df.index.intersection(labels.index)
    price = df.loc[common, "WTI_Crude_Close"]
    regimes = labels.loc[common]

    fig, ax = plt.subplots(figsize=(16, 6))
    for regime, color in COLORS.items():
        mask = regimes == regime
        ax.fill_between(price.index, 0, price.max() * 1.05,
                        where=mask, alpha=0.15, color=color, label=regime.title())
    ax.plot(price.index, price.values, 'k-', linewidth=0.7)
    ax.set_ylabel("WTI Price (USD)")
    ax.set_title("Oil Price with Market Regimes", fontweight="bold", fontsize=14)
    ax.legend(loc="upper left")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    ax.grid(True, alpha=0.2)
    fig.tight_layout()
    _save(fig, "01_price_regimes.png")


def plot_regime_characteristics(features, labels):
    """02 — Box plots of key metrics per regime."""
    common = features.index.intersection(labels.index)
    data = features.loc[common].copy()
    data["regime"] = labels.loc[common].values

    metrics = ["return_1d", "volatility_20d", "drawdown"]
    titles = ["Daily Returns", "20-Day Volatility", "Drawdown from Peak"]

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    for ax, col, title in zip(axes, metrics, titles):
        if col in data.columns:
            for regime in ["bull", "bear", "crisis"]:
                subset = data[data["regime"] == regime][col].dropna()
                if len(subset) > 0:
                    ax.boxplot(subset, positions=[list(COLORS.keys()).index(regime)],
                              widths=0.6, patch_artist=True,
                              boxprops=dict(facecolor=COLORS[regime], alpha=0.6))
            ax.set_title(title, fontweight="bold")
            ax.set_xticks(range(3))
            ax.set_xticklabels(["Bull", "Bear", "Crisis"])
            ax.grid(True, alpha=0.2)
    fig.suptitle("Regime Characteristics", fontweight="bold", fontsize=14, y=1.02)
    fig.tight_layout()
    _save(fig, "02_regime_characteristics.png")


def plot_transition_matrix(labels):
    """03 — Probability of switching between regimes."""
    regimes = ["bull", "bear", "crisis"]
    transitions = pd.DataFrame(0, index=regimes, columns=regimes, dtype=float)

    values = labels.values
    for i in range(len(values) - 1):
        if values[i] in regimes and values[i+1] in regimes:
            transitions.loc[values[i], values[i+1]] += 1

    row_sums = transitions.sum(axis=1)
    for regime in regimes:
        if row_sums[regime] > 0:
            transitions.loc[regime] = transitions.loc[regime] / row_sums[regime]

    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(transitions, annot=True, fmt=".2f", cmap="YlOrRd",
                vmin=0, vmax=1, linewidths=0.5, ax=ax,
                xticklabels=["Bull", "Bear", "Crisis"],
                yticklabels=["Bull", "Bear", "Crisis"])
    ax.set_title("Regime Transition Probabilities", fontweight="bold", fontsize=13)
    ax.set_xlabel("To"); ax.set_ylabel("From")
    fig.tight_layout()
    _save(fig, "03_transition_matrix.png")


def plot_regime_timeline(labels):
    """04 — Timeline strip showing regime over time."""
    fig, ax = plt.subplots(figsize=(16, 2))

    for regime, color in COLORS.items():
        mask = labels == regime
        ax.fill_between(labels.index, -0.5, 0.5,
                        where=mask, color=color, alpha=0.8)

    ax.set_yticks([])
    ax.set_title("Market Regime Timeline", fontweight="bold", fontsize=12)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=c, alpha=0.8, label=r.title()) for r, c in COLORS.items()]
    ax.legend(handles=legend_elements, loc="upper right", ncol=3, fontsize=9)
    fig.tight_layout()
    _save(fig, "04_regime_timeline.png")


def plot_factor_importance(importance_by_regime):
    """05 — THE MONEY CHART: top factors side by side per regime."""
    if not importance_by_regime:
        return

    regimes = list(importance_by_regime.keys())
    n_regimes = len(regimes)

    fig, axes = plt.subplots(1, n_regimes, figsize=(6 * n_regimes, 8), sharey=False)
    if n_regimes == 1:
        axes = [axes]

    for ax, regime in zip(axes, regimes):
        factors = importance_by_regime[regime]
        names = [f[0].replace("_", " ")[:25] for f in factors]
        values = [f[1] for f in factors]

        ax.barh(range(len(names)), values, color=COLORS.get(regime, "#888"), alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=9)
        ax.set_title(f"{regime.title()} Market", fontweight="bold", fontsize=12)
        ax.set_xlabel("Importance")
        ax.invert_yaxis()
        ax.grid(True, alpha=0.2, axis='x')

    fig.suptitle("Top Risk Factors by Market Regime", fontweight="bold", fontsize=15, y=1.02)
    fig.tight_layout()
    _save(fig, "05_factor_importance_by_regime.png")


def plot_regime_duration(labels):
    """06 — How long each regime typically lasts."""
    regimes_list = []
    current_regime = labels.iloc[0]
    current_start = labels.index[0]

    for i in range(1, len(labels)):
        if labels.iloc[i] != current_regime:
            duration = (labels.index[i] - current_start).days
            regimes_list.append({"regime": current_regime, "duration": duration})
            current_regime = labels.iloc[i]
            current_start = labels.index[i]

    duration = (labels.index[-1] - current_start).days
    regimes_list.append({"regime": current_regime, "duration": duration})

    regime_df = pd.DataFrame(regimes_list)

    fig, ax = plt.subplots(figsize=(10, 5))
    for regime, color in COLORS.items():
        subset = regime_df[regime_df["regime"] == regime]["duration"]
        if len(subset) > 0:
            ax.hist(subset, bins=20, color=color, alpha=0.6,
                    label=f"{regime.title()} (avg: {subset.mean():.0f} days)")

    ax.set_xlabel("Duration (days)")
    ax.set_ylabel("Count")
    ax.set_title("How Long Each Regime Lasts", fontweight="bold", fontsize=13)
    ax.legend()
    ax.grid(True, alpha=0.2)
    fig.tight_layout()
    _save(fig, "06_regime_duration.png")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# REPORT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def generate_report(features, labels, importance_by_regime):
    L = []; w = L.append
    w("=" * 65)
    w("  OIL MARKET REGIME ANALYSIS")
    w(f"  {datetime.now():%Y-%m-%d %H:%M:%S}")
    w("=" * 65)

    w(f"\n  Date range: {labels.index.min().date()} → {labels.index.max().date()}")
    w(f"  Total trading days: {len(labels)}")

    w(f"\n{'─' * 65}")
    w("  REGIME BREAKDOWN")
    w(f"{'─' * 65}")
    for regime in ["bull", "bear", "crisis"]:
        count = (labels == regime).sum()
        pct = count / len(labels) * 100
        avg_ret = features.loc[labels == regime, "return_1d"].mean() * 252 * 100 if count > 0 else 0
        avg_vol = features.loc[labels == regime, "volatility_20d"].mean() * 100 if count > 0 else 0
        w(f"    {regime.upper():>8s}: {count:>5d} days ({pct:>5.1f}%)  "
          f"avg annual return: {avg_ret:>+6.1f}%  avg vol: {avg_vol:>5.1f}%")

    w(f"\n{'─' * 65}")
    w("  KEY INSIGHT")
    w(f"{'─' * 65}")
    w("")
    w("  The risk factors driving oil prices are DIFFERENT in each regime:")

    if importance_by_regime:
        for regime, factors in importance_by_regime.items():
            w(f"\n    {regime.upper()} MARKET — top 5 factors:")
            for i, (feat, imp) in enumerate(factors[:5], 1):
                w(f"      #{i} {feat} (importance: {imp:.4f})")

    w(f"\n{'─' * 65}")
    w("  CURRENT STATE")
    w(f"{'─' * 65}")
    current = labels.iloc[-1]
    w(f"    Current regime: {current.upper()}")
    w(f"    As of: {labels.index[-1].date()}")

    streak = 1
    for i in range(len(labels) - 2, -1, -1):
        if labels.iloc[i] == current:
            streak += 1
        else:
            break
    w(f"    Duration: {streak} trading days in current regime")

    report = "\n".join(L)
    with open(str(REGIME_DIR / "regime_report.txt"), "w") as f:
        f.write(report)
    print(f"\n  ✓ Report saved")
    return report


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MAIN
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main():
    print("\n" + "=" * 60)
    print("  MARKET REGIME DETECTION")
    print("=" * 60)

    df = load_data()
    if df is None:
        return

    features = prepare_regime_features(df)
    if len(features) < 100:
        print("  ✗ Not enough data")
        return

    # Run all 3 methods
    hmm_labels = detect_hmm(features)
    kmeans_labels = detect_kmeans(features)
    rule_labels = detect_rulebased(features)

    # Use best available as primary (HMM > K-Means > Rules)
    if hmm_labels is not None:
        primary_labels = hmm_labels; method = "HMM"
    elif kmeans_labels is not None:
        primary_labels = kmeans_labels; method = "K-Means"
    else:
        primary_labels = rule_labels; method = "Rule-Based"

    print(f"\n  Primary method: {method}")

    # Save labels
    labels_df = pd.DataFrame(index=features.index)
    labels_df["primary_regime"] = primary_labels
    if hmm_labels is not None: labels_df["hmm_regime"] = hmm_labels
    if kmeans_labels is not None: labels_df["kmeans_regime"] = kmeans_labels
    labels_df["rule_regime"] = rule_labels
    labels_df.to_csv(str(REGIME_DIR / "regime_labels.csv"))
    print(f"  ✓ Labels saved")

    # Factor importance per regime
    print("\n" + "─" * 60)
    importance = compute_factor_importance(df, primary_labels)

    if importance:
        rows = []
        for regime, factors in importance.items():
            for feat, imp in factors:
                rows.append({"regime": regime, "feature": feat, "importance": round(imp, 4)})
        pd.DataFrame(rows).to_csv(str(REGIME_DIR / "regime_factor_importance.csv"), index=False)
        print(f"  ✓ Factor importance saved")

    # Plots
    print("\n" + "─" * 60)
    print("  GENERATING PLOTS")
    print("─" * 60)

    plot_price_with_regimes(df, primary_labels)
    plot_regime_characteristics(features, primary_labels)
    plot_transition_matrix(primary_labels)
    plot_regime_timeline(primary_labels)
    if importance: plot_factor_importance(importance)
    plot_regime_duration(primary_labels)

    # Report
    report = generate_report(features, primary_labels, importance)
    print("\n" + report)

    # JSON summary for API
    summary = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "method": method,
        "current_regime": primary_labels.iloc[-1],
        "regime_counts": {k: int(v) for k, v in primary_labels.value_counts().items()},
        "top_factors_by_regime": {
            regime: [{"feature": f, "importance": round(i, 4)} for f, i in factors[:5]]
            for regime, factors in (importance or {}).items()
        }
    }
    with open(str(REGIME_DIR / "regime_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\n{'=' * 60}")
    print(f"  DONE — {REGIME_DIR}/")
    print(f"  • regime_labels.csv")
    print(f"  • regime_factor_importance.csv")
    print(f"  • regime_report.txt")
    print(f"  • regime_summary.json")
    print(f"  • plots/ (6 charts)")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()